"""SUMO FCD trace reader and mobility provider — W15.

Replaces the RWP bounce model with pre-generated traces from the Bạch Mai MCI
convergence scenario (M10.2).  The FCD XML uses SUMO geo format (x=lon, y=lat);
this module converts GPS→metric via Haversine relative to the gNB anchor point.

Reference:
    sumo-user.pdf §FCD (Floating Car Data output)
    Guastella 2023 §netconvert + simulation workflow (traffic-modeling-with-sumo)
"""

from __future__ import annotations

import glob
import math
import os
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from functools import lru_cache

import numpy as np

# ---------------------------------------------------------------------------
# Default data paths (relative to this file)
# ---------------------------------------------------------------------------

_DATA_DIR: str = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "..", "data", "sumo")
)


def default_fcd_path(K: int) -> str:
    """Return the single-density (no background traffic) FCD path for a given K.

    This is the original trace used by W15-B1: ambulances only, no background
    vehicles. Equivalent to density="none" in the Tier-A sweep.
    """
    name = f"bachmaiHN_mci_k{K}.fcd.xml"
    return os.path.join(_DATA_DIR, name)


def density_fcd_path(K: int, density: str) -> str:
    """Return the Tier-A density-sweep FCD path for a given K and density.

    Density must be one of: "light", "medium", "heavy" (Tier-A training),
    or "light_smoke", "medium_smoke", "heavy_smoke" (smoke pipeline test).

    Files are generated by data/sumo/07_generate_density_sweep.py.
    If the file does not exist, FileNotFoundError is raised with a clear message.

    Simulation specs (declared — not Hà Nội ground truth):
      SIM_DURATION = 400s, STEP_LENGTH = 0.1s
      Background vehicles: light=67, medium=267, heavy=667 (scaled ×4/3 from 300s baseline)
      TLS: SUMO-generated via netconvert --tls.guess (heuristic, not field-measured)
    """
    _VALID = {"light", "medium", "heavy", "light_smoke", "medium_smoke", "heavy_smoke"}
    if density not in _VALID:
        raise ValueError(f"density must be one of {_VALID}, got {density!r}")
    density_dir = os.path.join(_DATA_DIR, "density")
    name = f"bachmaiHN_mci_k{K}_{density}.fcd.xml"
    path = os.path.join(density_dir, name)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Density FCD not found: {path}\n"
            f"Run: python3 data/sumo/07_generate_density_sweep.py"
        )
    return path


# ---------------------------------------------------------------------------
# gNB anchor — Bạch Mai Hospital (SSOT: utils/config.py BACH_MAI_LAT/LON)
# ---------------------------------------------------------------------------

from utils.config import BACH_MAI_LAT as GNB_LAT, BACH_MAI_LON as GNB_LON  # type: ignore[assignment]

_MPLD: float = 111_320.0                           # m per degree latitude
_MPLLON: float = _MPLD * math.cos(math.radians(GNB_LAT))   # m per degree lon at gNB lat


# ---------------------------------------------------------------------------
# Haversine GPS → metric
# ---------------------------------------------------------------------------

def gps_to_metric(lat: float, lon: float) -> tuple[float, float]:
    """Convert GPS (lat, lon) to metric (east_m, north_m) relative to gNB.

    Uses equirectangular approximation (Haversine-equivalent for small offsets
    < 5 km from reference point).  Error < 0.1% at 300 m.

    Reference: Haversine well-known formula; sumo-user.pdf §FCD geo coordinates.
    """
    north_m = (lat - GNB_LAT) * _MPLD
    east_m  = (lon - GNB_LON) * _MPLLON
    return east_m, north_m


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class VehicleSnapshot:
    vehicle_id: str
    x_m: float      # east of gNB (m)
    y_m: float      # north of gNB (m)
    speed_ms: float


@dataclass
class FcdTimestep:
    time_sec: float
    vehicles: list[VehicleSnapshot] = field(default_factory=list)


# ---------------------------------------------------------------------------
# FCD XML parser
# ---------------------------------------------------------------------------

@lru_cache(maxsize=16)
def _load_fcd_cached(fcd_path: str, vehicle_ids_key):
    """Cached parse keyed by (path, vehicle_ids). FCD files are immutable on disk,
    so parsing once per (path, ids) and replaying read-only is safe — this makes
    SUMO-backed env resets fast enough to be the default for ALL tests."""
    return _parse_fcd(fcd_path, list(vehicle_ids_key) if vehicle_ids_key is not None else None)


def load_fcd(fcd_path: str, vehicle_ids: list[str] | None = None) -> list[FcdTimestep]:
    """Parse SUMO FCD XML into a list of FcdTimestep (cached by path+ids)."""
    return _load_fcd_cached(fcd_path, tuple(vehicle_ids) if vehicle_ids is not None else None)


def _parse_fcd(fcd_path: str, vehicle_ids: list[str] | None = None) -> list[FcdTimestep]:
    """Uncached FCD XML parse.

    FCD geo format: <vehicle x=lon y=lat angle=deg speed=ms />.
    Vehicles not listed in `vehicle_ids` are silently ignored.
    Reference: sumo-user.pdf §FCD output format.
    """
    tree = ET.parse(fcd_path)
    root = tree.getroot()
    timesteps: list[FcdTimestep] = []
    for ts_el in root.iter("timestep"):
        t = float(ts_el.get("time", 0.0))
        ts = FcdTimestep(time_sec=t)
        for v_el in ts_el.iter("vehicle"):
            vid = v_el.get("id", "")
            if vehicle_ids is not None and vid not in vehicle_ids:
                continue
            lon = float(v_el.get("x", 0.0))   # SUMO geo: x=lon
            lat = float(v_el.get("y", 0.0))   # SUMO geo: y=lat
            speed = float(v_el.get("speed", 0.0))
            x_m, y_m = gps_to_metric(lat, lon)
            ts.vehicles.append(VehicleSnapshot(vid, x_m, y_m, speed))
        timesteps.append(ts)
    return timesteps


# ---------------------------------------------------------------------------
# Mobility provider
# ---------------------------------------------------------------------------

class SumoMobilityProvider:
    """Replay pre-generated FCD trace at the env TTI resolution.

    Steps through the trace, linearly interpolating between FCD timesteps
    (default 100ms) to match the simulator TTI (default 10ms).

    Non-present vehicles (exited FCD) report their last valid position rather
    than [0, 0], preventing false gNB proximity detection. FCD exit at the
    destination latches ``reached_destination_mask[k]`` so the env can detect
    arrival even when the vehicle disappears before reaching ``arrival_radius_m``.

    Usage:
        provider = SumoMobilityProvider(fcd_path, K=3, tti_sec=0.01,
                                         destination_xy_m=(45.07, 16.00),
                                         arrival_radius_m=15.0)
        pos_init = provider.reset()       # (K, 2) metric
        pos_next, vel = provider.step()   # (K, 2), (K, 2) m/s
    """

    def __init__(
        self,
        fcd_path: str,
        K: int,
        tti_sec: float = 0.01,
        destination_xy_m: tuple[float, float] | None = None,
        arrival_radius_m: float = 15.0,
    ) -> None:
        self.K = K
        self.tti_sec = tti_sec
        self._vehicle_ids = [f"amb_{k}" for k in range(K)]
        self._timesteps = load_fcd(fcd_path, vehicle_ids=self._vehicle_ids)
        if len(self._timesteps) < 2:
            raise ValueError(
                f"FCD trace has {len(self._timesteps)} timestep(s); need ≥2."
            )
        self._trace_duration = self._timesteps[-1].time_sec
        self._sim_time: float = 0.0

        # Destination for arrival detection (separate from gNB at origin).
        self._destination_xy_m: np.ndarray | None = (
            np.array(destination_xy_m, dtype=np.float64)
            if destination_xy_m is not None
            else None
        )
        self._arrival_radius_m = arrival_radius_m

        # Build sorted arrays for fast interpolation
        self._t_arr = np.array([ts.time_sec for ts in self._timesteps], dtype=np.float64)
        n_ts = len(self._timesteps)
        # Position array: (n_ts, K, 2) — zeros where vehicle absent
        self._pos_arr = np.zeros((n_ts, K, 2), dtype=np.float64)
        # Valid mask: (n_ts, K) — True where FCD has actual data for that vehicle
        self._valid_arr = np.zeros((n_ts, K), dtype=bool)
        for i, ts in enumerate(self._timesteps):
            veh_map = {v.vehicle_id: v for v in ts.vehicles}
            for k, vid in enumerate(self._vehicle_ids):
                if vid in veh_map:
                    v = veh_map[vid]
                    self._pos_arr[i, k, 0] = v.x_m
                    self._pos_arr[i, k, 1] = v.y_m
                    self._valid_arr[i, k] = True

        # Per-step mutable state — initialized by reset()
        self._last_valid_pos: np.ndarray = np.zeros((K, 2), dtype=np.float64)
        self._reached_dest_mask: np.ndarray = np.zeros(K, dtype=bool)
        self._prev_present_mask: np.ndarray = np.zeros(K, dtype=bool)
        self._present_mask: np.ndarray = np.zeros(K, dtype=bool)

        # Trajectory cache (built by build_trajectory_cache, consumed by step)
        self._traj_pos: np.ndarray | None = None
        self._traj_vel: np.ndarray | None = None
        self._traj_reached: np.ndarray | None = None
        self._traj_present: np.ndarray | None = None
        self._traj_idx: int = 0

    # ------------------------------------------------------------------
    # Trajectory cache — vectorized precompute (replaces 735K Python calls)
    # ------------------------------------------------------------------

    def build_trajectory_cache(self, n_ticks: int) -> None:
        """Precompute (pos, vel, present, reached_dest) for n_ticks future steps.

        Uses vectorized NumPy interpolation (single pass over the FCD arrays)
        instead of calling _interpolate() per tick. Then patches the few
        edge-case ticks where a vehicle exits the FCD (present→absent transition,
        arrival detection). Results are bit-for-bit identical to sequential step().
        """
        K = self.K
        t_start = self._sim_time
        t_all = t_start + np.arange(1, n_ticks + 1) * self.tti_sec
        t_prev_all = t_start + np.arange(0, n_ticks) * self.tti_sec

        # --- Vectorized interpolation for ALL ticks at once ---
        def _interp_batch(t_arr: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
            """(n, K, 2) positions + (n, K) present masks, vectorized."""
            n = len(t_arr)
            if self._trace_duration > 0:
                tw = t_arr % self._trace_duration
            else:
                tw = np.zeros(n)
            idx = np.searchsorted(self._t_arr, tw, side="right") - 1
            idx = np.clip(idx, 0, len(self._t_arr) - 2)
            t0 = self._t_arr[idx]
            t1 = self._t_arr[idx + 1]
            dt = t1 - t0
            alpha = np.where(dt > 0, (tw - t0) / dt, 0.0)
            pos = ((1.0 - alpha[:, None, None]) * self._pos_arr[idx]
                   + alpha[:, None, None] * self._pos_arr[idx + 1])
            present = self._valid_arr[idx].copy()
            # Transition fix: don't interpolate toward [0,0] for invalid right bracket
            right_invalid = self._valid_arr[idx] & ~self._valid_arr[idx + 1]
            for tick in np.where(right_invalid.any(axis=1))[0]:
                for k in range(K):
                    if right_invalid[tick, k]:
                        pos[tick, k] = self._pos_arr[idx[tick], k]
            return pos.astype(np.float64), present

        raw_new, present_new = _interp_batch(t_all)
        raw_prev, present_prev = _interp_batch(t_prev_all)

        # --- Build effective pos (frozen last_valid for non-present) ---
        eff_pos = raw_new.copy()
        eff_prev = raw_prev.copy()
        last_valid = self._last_valid_pos.copy()
        reached = self._reached_dest_mask.copy()

        traj_pos = np.empty((n_ticks, K, 2), dtype=np.float64)
        traj_vel = np.empty((n_ticks, K, 2), dtype=np.float64)
        traj_reached = np.empty((n_ticks, K), dtype=bool)
        traj_present = np.empty((n_ticks, K), dtype=bool)

        prev_present = self._prev_present_mask.copy()
        for i in range(n_ticks):
            # FCD exit detection + last_valid_pos update (sequential, few transitions)
            for k in range(K):
                was = bool(prev_present[k])
                now = bool(present_new[i, k])
                if was and not now and self._destination_xy_m is not None:
                    dx = last_valid[k, 0] - self._destination_xy_m[0]
                    dy = last_valid[k, 1] - self._destination_xy_m[1]
                    if math.sqrt(dx * dx + dy * dy) <= self._arrival_radius_m:
                        reached[k] = True
                if now:
                    last_valid[k] = raw_new[i, k]
                if not now:
                    eff_pos[i, k] = last_valid[k]
                if not present_prev[i, k] if i > 0 else not bool(self._present_mask[k]):
                    eff_prev[i, k] = last_valid[k] if not now else eff_prev[i, k]

            # Velocity: (eff_new - eff_prev) / dt, zero for non-present
            for k in range(K):
                if present_new[i, k]:
                    traj_vel[i, k] = (eff_pos[i, k] - eff_prev[i, k]) / self.tti_sec
                else:
                    traj_vel[i, k] = 0.0

            traj_pos[i] = eff_pos[i]
            traj_reached[i] = reached.copy()
            traj_present[i] = present_new[i]
            prev_present = present_new[i].copy()

        self._traj_pos = traj_pos
        self._traj_vel = traj_vel
        self._traj_reached = traj_reached
        self._traj_present = traj_present
        self._traj_idx = 0

    def reset(self) -> np.ndarray:
        """Reset to start of trace; return initial positions (K, 2) in metric."""
        self._sim_time = 0.0
        self._last_valid_pos = np.zeros((self.K, 2), dtype=np.float64)
        self._reached_dest_mask = np.zeros(self.K, dtype=bool)
        self._traj_pos = None
        self._traj_idx = 0

        raw_pos, present = self._interpolate(0.0)
        for k in range(self.K):
            if present[k]:
                self._last_valid_pos[k] = raw_pos[k].copy()
        self._prev_present_mask = present.copy()
        self._present_mask = present.copy()

        # Return effective positions (last_valid_pos for non-present)
        pos = raw_pos.copy()
        for k in range(self.K):
            if not present[k]:
                pos[k] = self._last_valid_pos[k]
        return pos.astype(np.float64)

    def step(self) -> tuple[np.ndarray, np.ndarray]:
        """Advance one TTI; return (new_pos (K,2), velocity (K,2)) in metric/m/s.

        Non-present vehicles return their last valid position with zero velocity.
        FCD exit at the destination latches reached_destination_mask.

        When a trajectory cache exists (build_trajectory_cache), returns
        precomputed values and updates internal state for external readers
        (reached_destination_mask, present_mask). Falls back to original
        computation when cache is exhausted or not built.
        """
        if (self._traj_pos is not None
                and self._traj_idx < len(self._traj_pos)):
            i = self._traj_idx
            self._traj_idx += 1
            self._sim_time += self.tti_sec
            self._reached_dest_mask = self._traj_reached[i].copy()
            self._present_mask = self._traj_present[i].copy()
            return self._traj_pos[i].copy(), self._traj_vel[i].copy()

        pos_old = self._effective_pos(self._sim_time)
        self._sim_time += self.tti_sec
        raw_new, present_now = self._interpolate(self._sim_time)

        # Detect FCD exit and update last_valid_pos / reached_dest_mask
        for k in range(self.K):
            was_present = bool(self._prev_present_mask[k])
            is_present = bool(present_now[k])
            if was_present and not is_present and self._destination_xy_m is not None:
                last = self._last_valid_pos[k]
                dx = last[0] - self._destination_xy_m[0]
                dy = last[1] - self._destination_xy_m[1]
                if math.sqrt(dx * dx + dy * dy) <= self._arrival_radius_m:
                    self._reached_dest_mask[k] = True
            if is_present:
                self._last_valid_pos[k] = raw_new[k].copy()

        # Effective new positions (frozen for non-present; zero vel for stopped)
        pos_new = raw_new.copy()
        vel = np.zeros((self.K, 2), dtype=np.float64)
        for k in range(self.K):
            if not present_now[k]:
                pos_new[k] = self._last_valid_pos[k]
            else:
                vel[k] = (pos_new[k] - pos_old[k]) / self.tti_sec

        self._prev_present_mask = present_now.copy()
        self._present_mask = present_now.copy()
        return pos_new.astype(np.float64), vel.astype(np.float64)

    def advance_until_within(self, radius_m: float) -> tuple[np.ndarray, np.ndarray, bool]:
        """Vectorized fast-forward to the first FCD timestep where any PRESENT
        ambulance is within ``radius_m`` of the origin (gNB). Sets internal state
        to that time and returns (effective_pos (K,2), velocity (K,2), found).

        Replaces a per-TTI step loop (O(trace_duration / tti) ~ 4·10^5 steps) with
        an O(n_timesteps) numpy search — identical cell-entry semantics up to FCD
        resolution (~0.1 s ⇒ <1 m on a 1 km boundary), since the destination lies
        INSIDE the cell so no arrival can latch before entry. Used by the env reset
        fast-forward that defines the RL episode start.
        """
        dist = np.linalg.norm(self._pos_arr, axis=2)          # (n_ts, K) dist from gNB
        within = (dist <= radius_m) & self._valid_arr          # present AND within cell
        hits = np.nonzero(within.any(axis=1))[0]
        if len(hits) == 0:
            target_idx = len(self._t_arr) - 1                  # never enters → seek to end
            found = False
        else:
            target_idx = int(hits[0])
            found = True
        target_t = float(self._t_arr[target_idx])

        # Reset latches then set state at the entry time (no arrival before entry).
        self._sim_time = target_t
        self._reached_dest_mask = np.zeros(self.K, dtype=bool)
        raw, present = self._interpolate(target_t)
        for k in range(self.K):
            if present[k]:
                self._last_valid_pos[k] = raw[k].copy()
        self._prev_present_mask = present.copy()
        self._present_mask = present.copy()

        pos = self._effective_pos(target_t)
        # Velocity from the interpolation derivative at the entry time.
        raw_next, present_next = self._interpolate(target_t + self.tti_sec)
        vel = np.zeros((self.K, 2), dtype=np.float64)
        for k in range(self.K):
            if present[k] and present_next[k]:
                vel[k] = (raw_next[k] - raw[k]) / self.tti_sec
        return pos.astype(np.float64), vel.astype(np.float64), found

    def _effective_pos(self, t: float) -> np.ndarray:
        """Effective position at time t — last_valid_pos for non-present vehicles."""
        raw, present = self._interpolate(t)
        pos = raw.copy()
        for k in range(self.K):
            if not present[k]:
                pos[k] = self._last_valid_pos[k]
        return pos.astype(np.float64)

    def _interpolate(self, t: float) -> tuple[np.ndarray, np.ndarray]:
        """Linear interpolation at time t (wraps around trace).

        Returns (pos (K,2), present_mask (K,)) where present_mask[k]=True
        iff the vehicle has valid FCD data at the left-bracket timestep.
        Transition case (left-valid, right-invalid) uses left bracket directly
        to avoid interpolating toward [0,0].
        """
        if self._trace_duration > 0:
            t_wrapped = t % self._trace_duration
        else:
            t_wrapped = 0.0

        idx = np.searchsorted(self._t_arr, t_wrapped, side="right") - 1
        idx = int(np.clip(idx, 0, len(self._t_arr) - 2))
        t0 = self._t_arr[idx]
        t1 = self._t_arr[idx + 1]
        dt = t1 - t0
        alpha = (t_wrapped - t0) / dt if dt > 0 else 0.0

        present = self._valid_arr[idx].copy()
        pos = (1.0 - alpha) * self._pos_arr[idx] + alpha * self._pos_arr[idx + 1]

        # Fix transition: don't interpolate toward [0,0] for invalid right brackets
        for k in range(self.K):
            if self._valid_arr[idx, k] and not self._valid_arr[idx + 1, k]:
                pos[k] = self._pos_arr[idx, k]

        return pos.astype(np.float64), present

    @property
    def present_mask(self) -> np.ndarray:
        """Current presence mask (K,) bool — True if vehicle in FCD this step."""
        return self._present_mask.copy()

    @property
    def reached_destination_mask(self) -> np.ndarray:
        """Latched arrival mask (K,) bool — True once vehicle exited FCD at dest."""
        return self._reached_dest_mask.copy()

    @property
    def last_valid_pos(self) -> np.ndarray:
        """Last known positions (K, 2) metric — frozen at last valid FCD entry."""
        return self._last_valid_pos.copy()


# ---------------------------------------------------------------------------
# PooledSumoMobilityProvider — F3: multi-scenario route pool
# ---------------------------------------------------------------------------

class PooledSumoMobilityProvider:
    """Manages a pool of FCD trace paths; samples one per episode by index.

    On each reset(trace_idx), selects route_pool[trace_idx % len(pool)] and
    instantiates a fresh SumoMobilityProvider for that trace. Passes destination
    params through so arrival detection works correctly.

    NOTE: Tier-A diversity (density-variant traces) requires real SUMO reruns.
    This class only manages selection from the given pool — if all paths point
    to the same trace, behavior is identical to a single SumoMobilityProvider.
    """

    def __init__(
        self,
        route_pool: list[str],
        K: int,
        tti_sec: float,
        destination_xy_m: tuple[float, float] | None = None,
        arrival_radius_m: float = 15.0,
    ) -> None:
        if not route_pool:
            raise ValueError("route_pool must be non-empty")
        self._pool = list(route_pool)
        self._K = K
        self._tti_sec = tti_sec
        self._destination_xy_m = destination_xy_m
        self._arrival_radius_m = arrival_radius_m
        self._active: SumoMobilityProvider | None = None

    def reset(self, trace_idx: int = 0) -> np.ndarray:
        """Select trace by index and reset to t=0.

        trace_idx is wrapped modulo pool size so any non-negative value is valid.
        Route is non-cyclic (origin → BV Bạch Mai); always starts from t=0 to
        avoid teleporting vehicles back to origin mid-episode.
        Default 0 gives the original deterministic behaviour.
        """
        path = self._pool[trace_idx % len(self._pool)]
        self._active = SumoMobilityProvider(
            path,
            K=self._K,
            tti_sec=self._tti_sec,
            destination_xy_m=self._destination_xy_m,
            arrival_radius_m=self._arrival_radius_m,
        )
        return self._active.reset()

    def step(self) -> tuple[np.ndarray, np.ndarray]:
        """Delegate to the active provider."""
        if self._active is None:
            raise RuntimeError("PooledSumoMobilityProvider.step() called before reset()")
        return self._active.step()

    def advance_until_within(self, radius_m: float) -> tuple[np.ndarray, np.ndarray, bool]:
        """Delegate vectorized cell-entry fast-forward to the active provider."""
        if self._active is None:
            raise RuntimeError("advance_until_within() called before reset()")
        return self._active.advance_until_within(radius_m)

    def build_trajectory_cache(self, n_ticks: int) -> None:
        """Delegate trajectory precompute to the active provider."""
        if self._active is None:
            raise RuntimeError("build_trajectory_cache() called before reset()")
        self._active.build_trajectory_cache(n_ticks)

    @property
    def present_mask(self) -> np.ndarray:
        if self._active is None:
            return np.zeros(self._K, dtype=bool)
        return self._active.present_mask

    @property
    def reached_destination_mask(self) -> np.ndarray:
        if self._active is None:
            return np.zeros(self._K, dtype=bool)
        return self._active.reached_destination_mask

    @property
    def last_valid_pos(self) -> np.ndarray:
        if self._active is None:
            return np.zeros((self._K, 2), dtype=np.float64)
        return self._active.last_valid_pos


def default_route_pool(K: int) -> list[str]:
    """Return the full training pool for a given K.

    Pool composition (in priority order):
      1. Tier-A base traces (3 files): light/medium/heavy, fixed routes.
         Generated by 07_generate_density_sweep.py.
      2. Random-start variant traces (N×3 files): N random starting positions
         × 3 densities (light/medium/heavy).
         Generated by 08_generate_random_route_pool.py.

    If neither source exists, falls back to the single no-background trace so
    existing tests keep passing without running any generation scripts.

    Pool size examples:
      Base only (no variants):   3 files  → 3 distinct (route, density) combos
      30 variants generated:    93 files  → 93 distinct (route, density) combos

    PooledSumoMobilityProvider selects uniformly at random each episode via
    rng.integers(0, len(pool)), giving full (route × density) diversity.
    """
    density_dir = os.path.join(_DATA_DIR, "density")
    tier_a_densities = ["light", "medium", "heavy"]
    tier_a_paths = [
        os.path.join(density_dir, f"bachmaiHN_mci_k{K}_{d}.fcd.xml")
        for d in tier_a_densities
    ]

    if not all(os.path.exists(p) for p in tier_a_paths):
        # Tier-A base not generated yet — single no-background fallback.
        return [default_fcd_path(K)]

    # Discover variant files produced by 08_generate_random_route_pool.py.
    variants_dir = os.path.join(density_dir, "variants")
    variant_paths: list[str] = sorted(
        glob.glob(
            os.path.join(variants_dir, f"bachmaiHN_mci_k{K}_v*_*.fcd.xml")
        )
    )

    return tier_a_paths + variant_paths


# ---------------------------------------------------------------------------
# SINR range sanity helper (used in tests)
# ---------------------------------------------------------------------------

def distance_range_m(fcd_path: str, K: int) -> tuple[float, float]:
    """Return (min_dist_m, max_dist_m) across all vehicles and timesteps."""
    timesteps = load_fcd(fcd_path, vehicle_ids=[f"amb_{k}" for k in range(K)])
    dists: list[float] = []
    for ts in timesteps:
        for v in ts.vehicles:
            dists.append(math.sqrt(v.x_m ** 2 + v.y_m ** 2))
    if not dists:
        return 0.0, 0.0
    return min(dists), max(dists)
